#!/usr/bin/env bash
set -euo pipefail

# MF_PROJECT_ROOT must always be defined.
export MF_PROJECT_ROOT="${MF_PROJECT_ROOT:-$(pwd)}"

# Check if we've already got the na4ma4 core library.
if [[ ! -d ".makefiles/ext/na4ma4/cache" ]]; then
    tmpdir="$(mktemp -d)"
    trap "rm -rf '${tmpdir}'" EXIT

    # Download the na4ma4 core library.
    curl \
        --fail \
        --silent \
        --show-error \
        --location \
        --create-dirs \
        --output "${tmpdir}/main.zip" \
        "https://github.com/na4ma4/makefiles-ext/archive/main.zip"

    # Unpack the library into the .makefiles directory.
    unzip -q "${tmpdir}/main.zip" -d "${tmpdir}"
    mv "${tmpdir}/main.zip" "${tmpdir}/makefiles-ext-main/v1/main.zip"
    mkdir -p ".makefiles/ext/na4ma4/cache"
    cp -r "${tmpdir}/makefiles-ext-main/v1"/* ".makefiles/ext/na4ma4/cache/"
fi

if [[ ! -d ".makefiles/ext/na4ma4/core" ]]; then
    mkdir -p ".makefiles/ext/na4ma4/core"
    cp -r ".makefiles/ext/na4ma4/cache/core"/* ".makefiles/ext/na4ma4/core/"
fi

# # Finally, invoke the build-resource command to produce the actual resource that
# # was requested.
.makefiles/ext/na4ma4/core/bin/na4ma4-build-resource "${1}"
